baseURL       = "https://itaygueta.com/"
languageCode  = "en-us"
title         = "Itay Gueta"
theme        = "ananke"
[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
    [markup.goldmark.renderer]
  unsafe = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"
    title = "Itay Gueta"
    languageCode = "en-us"
  [languages.de]
    languageName = "Deutsch"
    weight = 2
    contentDir = "content/de"
    title = "Itay Gueta"
    languageCode = "de"
